name: Main workflow
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Build application
        run: ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: "m17k0"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
