name: Main workflow
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Set up SonarCloud
        run: |
          export SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
          export SONAR_PROJECT_KEY="${{ secrets.SONAR_PROJECT_KEY }}"
        
      - name: Build application
        run: ci/build-app.sh

      - name: Test
        run: ci/unit-test-app.sh

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
